### ISSUE TITLE
[BUG] upgrading from 2.10.0 breaks nextjs app

### ISSUE THREAD

**Issue by shrugs** [juliencrn/usehooks-ts#461] opened 2024-02-01 19:45 UTC
### Describe the bug

using any version above 2.10.0 breaks my next build with

```
Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'length')
at eb (/Users/matt/projects/project/apps/app/.next/server/chunks/7199.js:1:24143)
```

### To Reproduce

-

### Expected behavior

-

### Additional context

-

**Comment by juliencrn** [comment] 2024-02-02 11:22
Hi, thanks for the report. 
Unfortunately, I'll close it because you have not given a minimal bug reproduction. I've just tested `2.12.0` on a fresh Next.js app, and it works as expected. 
I would recommend you to use the latest release (`2.12.1`).
Feel free to re-open an issue with more information if your problem persists.

**Closed by juliencrn** 2024-02-02 11:22 UTC
Labels: bug
