### ISSUE TITLE
Error parsing data that are stored manually or by other means

### ISSUE THREAD

**Issue by oviirup** [juliencrn/usehooks-ts#188] opened 2022-07-24 18:30 UTC
When you set a local-storage item manually or by other means which is not using the hook, it throws an error.

I am using a custom script to store `theme` info which is just a string, so it does not need to be stringified. But when I am accessing the stored item using the hook it is sending `undefined`.

### Local storage
`theme` : `dark`
### Relevant log output
```
parsing error on {value: 'dark'}
```

### Possible cause
This is probably happening because of the `psrseJson` function

```
function parseJSON<T>(value: string | null): T | undefined {
  try {
    return value === 'undefined' ? undefined : JSON.parse(value ?? '')
  } catch {
    console.log('parsing error on', { value })
    return undefined
  }
}
```

**Comment by juliencrn** [comment] 2024-01-07 23:59
Duplicate of #240

**Closed by juliencrn** 2024-01-07 23:59 UTC
Labels: bug, duplicate
